version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHODIKAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile_volumens.yml
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app

  test:
    stdin_open: true
    environment:
      - CHODIKAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockefile_volumens.yml
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm, "run", "test]
